[package]
name = "twilightpage"
version = "0.1.1"
entrypoint = "src/twilightpage.typ"
authors = ["Vsevolod Shegolev <https://github.com/vsheg>"]
homepage = "https://twilightpage.vsheg.com"
repository = "https://github.com/vsheg/twilightpage"
license = "MIT"
description = "Responsive web layout with wide margins, elegant sidenotes, and restrained typography. (TwilightPage fork)"
compiler = "0.14.0"
exclude = ["tests"]
categories = ["layout", "utility"]
keywords = ["website"]

[template]
path = "template"
entrypoint = "config.typ"
thumbnail = "assets/thumbnail.png"
